# Generated by Django 3.0.4 on 2020-03-20 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appusers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('text', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('text', models.CharField(max_length=100, unique=True)),
                ('test_id', models.ManyToManyField(to='test_app.Tests')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('is_correct', models.BooleanField(default=False)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.Questions')),
            ],
        ),
        migrations.CreateModel(
            name='Useranswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.Answers')),
                ('tests_questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.Questions')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.Appusers')),
            ],
            options={
                'unique_together': {('user_id', 'tests_questions')},
            },
        ),
        migrations.CreateModel(
            name='tests_questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.Questions')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.Tests')),
            ],
            options={
                'unique_together': {('test_id', 'question_id')},
            },
        ),
    ]
