# Generated by Django 3.0.4 on 2020-03-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyFirstModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('text_column', models.TextField(null=True)),
                ('bool_column', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('bin_column', models.BinaryField(null=True)),
                ('email_column', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
