# Generated by Django 3.0.4 on 2020-03-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfirstmodel',
            name='number_column',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
