# Generated by Django 3.0.4 on 2020-04-03 16:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200324_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_name', models.CharField(max_length=50)),
                ('exception_value', models.CharField(max_length=250)),
                ('exception_tb', models.TextField()),
                ('request_method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('query', django.contrib.postgres.fields.jsonb.JSONField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/%Y/%m/%d/'),
        ),
    ]
