# Generated by Django 3.0.4 on 2020-04-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200324_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error505',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.PositiveSmallIntegerField()),
                ('body', models.TextField()),
                ('time_period', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ошибка 505',
                'verbose_name_plural': 'Ошибки 505',
            },
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/%Y/%m/%d/'),
        ),
    ]
